version: '3.9'
services:
  postgresql:
    image: postgres:12
    container_name: postgresCuisine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: batiCuisine
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data